const AI_SITES = {'chatgpt.com':'ChatGPT','chat.openai.com':'ChatGPT','claude.ai':'Claude','gemini.google.com':'Gemini','aistudio.google.com':'Google AI Studio','perplexity.ai':'Perplexity','copilot.microsoft.com':'Microsoft Copilot','poe.com':'Poe','grok.com':'Grok','x.ai':'Grok','chat.deepseek.com':'DeepSeek','mistral.ai':'Mistral','lechat.mistral.ai':'Le Chat','notebooklm.google.com':'NotebookLM','meta.ai':'Meta AI','huggingface.co':'Hugging Face'};
const DETECTORS = [
{id:'secret',label:'API / access secret',severity:'critical',patterns:[/\bsk-[A-Za-z0-9_-]{20,}\b/g,/\bAKIA[0-9A-Z]{16}\b/g,/\bAIza[0-9A-Za-z_-]{20,}\b/g,/\bgh[pousr]_[A-Za-z0-9_]{20,}\b/g,/\bxox[baprs]-[A-Za-z0-9-]{20,}\b/g,/\bglpat-[A-Za-z0-9_-]{20,}\b/g]},
{id:'credential',label:'Credential / password',severity:'critical',patterns:[/(password|passwd|pwd|secret|api[_ -]?key|access[_ -]?token)\s*[:=]\s*['"`]?[^\s'"`]{6,}/gi,/-----BEGIN (?:RSA |EC |OPENSSH |DSA )?PRIVATE KEY-----[\s\S]+?-----END (?:RSA |EC |OPENSSH |DSA )?PRIVATE KEY-----/g,/\beyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\b/g]},
{id:'pii',label:'Personal information',severity:'high',patterns:[/\b[A-Z]{5}[0-9]{4}[A-Z]\b/g,/(?<!\d)\d{4}\s?\d{4}\s?\d{4}(?!\d)/g,/\b(?:\+?91[- .]?)?[6-9]\d{9}\b/g,/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi,/\b\d{3}-\d{2}-\d{4}\b/g]},
{id:'financial',label:'Financial data',severity:'high',patterns:[/\b(?:\d[ -]?){13,19}\b/g,/\b(?:IFSC|MICR)\s*[:=-]?\s*[A-Z0-9]{8,12}\b/gi]},
{id:'code',label:'Source code / internal code',severity:'medium',patterns:[/\b(?:BEGIN|END)\s+(?:RSA|OPENSSH|EC|PGP)\b/g,/\b(?:SELECT|INSERT|UPDATE|DELETE)\s+.+\s+FROM\s+/gi,/\b(?:INTERNAL|PROD|STAGING)_[A-Z0-9_]{4,}\b/g]}
];
let settings={enabled:true,mode:'block',aiOnly:false,allowlist:[],blocklist:[],customKeywords:['confidential','internal only','do not share','production credential','secret','proprietary','customer data'],enabledDetectors:['secret','credential','pii','financial','code','keyword']};
chrome.storage.local.get(settings).then(x=>settings={...settings,...x}); chrome.storage.onChanged.addListener(c=>{for(const k in c) settings[k]=c[k].newValue;});
function site(){const h=location.hostname.toLowerCase(); const k=Object.keys(AI_SITES).find(x=>h===x||h.endsWith('.'+x)); return {host:h,ai:!!k,name:k?AI_SITES[k]:h};}
function isAllowed(){return settings.allowlist.some(x=>x&&location.hostname.toLowerCase().includes(x.toLowerCase()));}
function isBlocked(){return settings.blocklist.some(x=>x&&location.hostname.toLowerCase().includes(x.toLowerCase()));}
function analyze(text){const findings=[]; const seen=new Set(); for(const d of DETECTORS){if(!(settings.enabledDetectors||[]).includes(d.id)) continue; for(const p0 of d.patterns){const p=new RegExp(p0.source,p0.flags); let m; while((m=p.exec(text))){const key=d.id+'|'+m.index+'|'+m[0]; if(!seen.has(key)){seen.add(key);findings.push({id:d.id,label:d.label,severity:d.severity,start:m.index,end:m.index+m[0].length,match:m[0]});} if(!p.global)break;}}} for(const kw of settings.customKeywords||[]){const i=text.toLowerCase().indexOf(kw.toLowerCase());if(i>=0)findings.push({id:'keyword',label:'Sensitive keyword',severity:'medium',start:i,end:i+kw.length,match:text.slice(i,i+kw.length)});} return findings.sort((a,b)=>a.start-b.start);}
function redact(text,fs){let o=text;[...fs].sort((a,b)=>b.start-a.start).forEach(f=>o=o.slice(0,f.start)+'[REDACTED:'+f.label.toUpperCase()+']'+o.slice(f.end));return o;}
function risk(fs){return fs.some(x=>x.severity==='critical')?'critical':fs.some(x=>x.severity==='high')?'high':fs.length?'medium':'none';}
function extractEditable(el){if(el instanceof HTMLTextAreaElement||el instanceof HTMLInputElement)return el.value; if(el.isContentEditable)return el.innerText; return '';}
function setEditable(el,text){if(el instanceof HTMLTextAreaElement||el instanceof HTMLInputElement){const setter=Object.getOwnPropertyDescriptor(Object.getPrototypeOf(el),'value')?.set;if(setter)setter.call(el,text);else el.value=text;el.dispatchEvent(new Event('input',{bubbles:true}));}else if(el.isContentEditable){el.focus();document.execCommand('selectAll',false);document.execCommand('insertText',false,text);}}
function showDialog(el,text,fs,action){if(document.getElementById('sg-dialog'))return false; const box=document.createElement('div');box.id='sg-dialog';box.style='position:fixed;z-index:2147483647;inset:0;background:rgba(0,0,0,.45);display:flex;align-items:center;justify-content:center;font:14px system-ui;color:#111';const card=document.createElement('div');card.style='background:white;width:min(520px,92vw);border-radius:14px;padding:22px;box-shadow:0 20px 60px rgba(0,0,0,.35)';card.innerHTML=`<h2 style="margin:0 0 8px">🛑 Sensitive information detected</h2><p style="margin:0 0 14px">Destination: <b>${site().name}</b></p><div style="background:#f6f6f6;border-radius:10px;padding:12px;margin-bottom:14px"><b>Risk: ${risk(fs).toUpperCase()}</b><br>${fs.map(x=>`• ${x.label}`).join('<br>')}</div><p>This message is still local to your browser.</p><div style="display:flex;gap:8px;justify-content:flex-end"><button id="sg-cancel">Cancel</button><button id="sg-redact">Remove sensitive data & continue</button><button id="sg-send">Send anyway</button></div>`;box.appendChild(card);document.documentElement.appendChild(box);card.querySelector('#sg-cancel').onclick=()=>box.remove();card.querySelector('#sg-redact').onclick=()=>{setEditable(el,redact(text,fs));box.remove(); chrome.runtime.sendMessage({type:'event',event:{action:'redacted',site:site().name,findings:fs.map(x=>x.label)}});};card.querySelector('#sg-send').onclick=()=>{box.remove();action(true);chrome.runtime.sendMessage({type:'event',event:{action:'warn',site:site().name,findings:fs.map(x=>x.label)}});};return true;}
function guard(el,action){if(!settings.enabled||isAllowed())return action();const s=site();if(settings.aiOnly&&!s.ai)return action();const text=extractEditable(el);if(!text)return action();const fs=analyze(text);if(!fs.length)return action();if(isBlocked()||settings.mode==='block'){showDialog(el,text,fs,()=>{});chrome.runtime.sendMessage({type:'event',event:{action:'block',site:s.name,findings:fs.map(x=>x.label)}});return false;}return showDialog(el,text,fs,action);}
document.addEventListener('keydown',e=>{if(e.key!=='Enter'||e.shiftKey)return;const t=e.target;if(!(t instanceof HTMLElement))return;let form=t.closest('form');let button=form?.querySelector('button[type="submit"],button:not([type])');if(!button && (t.isContentEditable||t.tagName==='TEXTAREA')){button=[...document.querySelectorAll('button')].find(b=>/send|submit|ask|generate/i.test(b.innerText||b.getAttribute('aria-label')||''));}if(button){const txt=extractEditable(t);const fs=analyze(txt);if(fs.length&&!settings.allowlist.some(x=>location.hostname.includes(x))){e.preventDefault();e.stopImmediatePropagation();guard(t,()=>button.click());}}},true);
document.addEventListener('click',e=>{const b=e.target?.closest?.('button,[role="button"]');if(!b)return;if(!/send|submit|ask|generate|search/i.test((b.innerText||b.getAttribute('aria-label')||'').trim()))return;const candidates=[...document.querySelectorAll('textarea,input,[contenteditable="true"]')].filter(x=>x.offsetParent!==null);const el=candidates.sort((a,b)=>{const ra=a.getBoundingClientRect(),rb=b.getBoundingClientRect();return (innerHeight-ra.bottom)-(innerHeight-rb.bottom)})[0];if(!el)return;const text=extractEditable(el);const fs=analyze(text);if(!fs.length)return;e.preventDefault();e.stopImmediatePropagation();guard(el,()=>b.click());},true);
